apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fdzm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fdzm
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fdzm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fdzm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fdzm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nobk-tenant/rhtap-demo-app/hacbs-test-project-fdzm@sha256:5f5c838d926dd901950fdd7cab4ba7374d9fa9998522e3d56171b718cb20e471
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
