apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fdzm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nobk-tenant/rhtap-demo-app/hacbs-test-project-fdzm@sha256:5f5c838d926dd901950fdd7cab4ba7374d9fa9998522e3d56171b718cb20e471
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
