apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fdzm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nobk-tenant/rhtap-demo-app/hacbs-test-project-fdzm@sha256:3574f4eb767be921a1f8c2697a7c8c213ccf657464bf16abcb9c02a46cdd5d1c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
